services:
  nginx-service:
    image: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

  sosuweb-render-service:
    build:
      context: .
      dockerfile: ./SosuWeb.Render/Dockerfile
    depends_on:
      db-service:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_HTTP_PORTS: 5000

  sosuweb-service:
    build:
      context: .
      dockerfile: ./SosuWeb/Dockerfile
    depends_on:
      - sosuweb-render-service
      - db-service
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_HTTP_PORTS: 5001
      
  db-service:
    image: postgres:17-alpine
    restart: unless-stopped
    secrets:
      - db-password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sosubot_renderer
      POSTGRES_USER: sosubot
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sosubot", "-d", "sosubot_renderer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

      
secrets:
  db-password:
    file: .secrets/.db_password