services:
  nginx-service:
    image: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/shoukko.de-cf.pem:/etc/ssl/shoukko.de-cf.pem
     - ./nginx/shoukko.de-cf.key:/etc/ssl/shoukko.de-cf.key
     - ./nginx/authenticated_origin_pull_ca.pem:/etc/ssl/authenticated_origin_pull_ca.pem
    ports:
     - "443:443"
    environment:
     - NGINX_HOST=sosubot.shoukko.de
     - NGINX_PORT=80
    depends_on:
      - sosuweb-service
      - sosuweb-render-service
    networks:
      - custom

  sosuweb-render-service:
    build:
      context: .
      dockerfile: ./SosuWeb.Render/Dockerfile
    volumes:
     - ./SosuWeb.Render/skins:/app/skins
     - ./SosuWeb.Render/videos:/app/videos
     - ./SosuWeb.Render/replays:/app/replays
    depends_on:
      db-service:
        condition: service_healthy
    expose:
      - "5000"
    environment:
      ASPNETCORE_HTTP_PORTS: 5000
    networks:
      - custom

  sosuweb-service:
    build:
      context: .
      dockerfile: ./SosuWeb/Dockerfile
    depends_on:
      - sosuweb-render-service
      - db-service
    expose:
      - "5001"
    environment:
      ASPNETCORE_HTTP_PORTS: 5001
    networks:
      - custom

  db-service:
    image: postgres:17-alpine
    restart: unless-stopped
    secrets:
      - db-password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sosubot_renderer
      POSTGRES_USER: sosubot
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sosubot", "-d", "sosubot_renderer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - custom

secrets:
  db-password:
    file: .secrets/.db_password

networks:
    custom:
      enable_ipv6: true
      driver: bridge